name: Rescue Community Church
favicon: null
layout_spectrum: 0.9551853237207979
typography_spectrum: 0.2479725470766425
title: Rescue. Renew. Repeat.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f201f'
    - '#ffffff'
    - '#282828'
    - '#d3a5a5'
    - '#767676'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
